# Generated by Django 5.1.7 on 2025-05-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='categoria',
        ),
    ]
